FROM nginx:latest

RUN echo "Hello from nginx: v1" > /usr/share/nginx/html/index.html

RUN echo "Hello from nginx: v2" > /usr/share/nginx/html/index.html

RUN echo "Hello From nginx: v3" > /usr/share/nginx/html/index.html